name: Deploy to Vercel on main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel deploy hook
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_9xaB8fJxkkWlIqdg8cG96UAu5yUG/KIUqa55YaJ
